---
# Source: example-hasura-promote/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-prod-env
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/example-hasura.git
    targetRevision: v0.15.1
    helm:
      version: v3
  destination:
    namespace: example-prod-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
