apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-prod-env
  source:
    path: charts/example-hasura
    repoURL: https://github.com/cloudnativeentrepreneur/example-hasura.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
      version: v3
  destination:
    namespace: example-prod-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

