apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-web3auth-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-prod-env
  source:
    path: charts/web3auth-db
    repoURL: https://github.com/cloudnativeentrepreneur/web3auth-db.git
    targetRevision: HEAD
    helm:
      version: v3
  destination:
    namespace: example-prod-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

